
export const InitialState = {
    dataApp:{
        URL_SERVER:false,
        DATA_RICHE_TEXT:"",
        PAGINA_SIGUIENTE :"",
        USER_ID :"",
        USER_NAME :"",
        USER_LINK_PHOTO :"",
        VALIDAR_USER :false,
        LOGIN_SPINNER :false,
        RESP_ERROR_LOGIN :"",
        ERROR_USER :false,
        PDF_VIEW_FORM :null,
        URL_PDF :null,
        EXAMEN_ID :"",
        CARGAR_COMMENT:false, 
        ADD_COMMENT_SPINNER :false,
        ADD_COMMENT_RESPONSE_SPINNER :false,
        CARGAR_RESPONSE_COMENT :false,
        ADD_RESPONSE_RESPONSE_SPINNER :false,
        CARGAR_RESPONSE_RESPONSE :false,
        SPINNER_CARGAR_EXAMENES:false,
        
    },
    dataRicheText:"",
    dataComent:[],
    paginaSiguiente:"",
    userId :"001",
    userName:"MX SOFTWARE",
    userLinkPhoto:"HTTP",
    validarUser:false,
    loginSpinner:false,
    errorResponseLogin:"",
    userError:false,
    examId:"",
    pdfUrl:null,
    formPdfView:null,
    spinnerComment:false,
    spinnerAddComment:false,
    spinnerAddCommentRespons:false,
    spinnerCargarCommentRespons:false,
    spinnerAddResponsRespons:false,
    spinnerCargarResponsRespons:false,
    spinnerCargarExamenes:false,
}